### ISSUE TITLE
planning for panel event

### ISSUE THREAD

**Issue by amyqcs** [BPR-Data-Team/ElectionModel2024-site#178]
### Machine Learning and the Political Process (tentative title)

**Panel statement:** Aiming to garner interest among Brown community members immersed in both politics and technology, this event seeks to provide insight on how the machine learning boom will impact the political process. Bringing together a professor with machine learning expertise, a politico, and a student creating a product at the nexus of the tech and politics spaces, attendees will hear how different perspectives inform perceptions of tomorrow’s politics. A student will moderate this event.

### Panel Event Overview
Preferred Locations: Joukowsky Forum at 111 Thayer St. or True North Classroom (Room 101) at 280 Brook Street
Duration: 60 minutes

**Speakers**
Moderator: student
24cast.org Leader: Asher Labovich (Founder)
Industry Panelist
Academic Panelist

Event materials: 4 chairs and waters for the speakers; light refreshments for attendees (cookie platter, fruit platter, etc.)
A/V needs: 4 lavalier or dynamic microphones for the speakers; 2 dynamic microphones w/ microphone stands for audience Q&A; projector(s); projector screen(s); USB-C projector connector

Google document w/ event details & action items: [https://docs.google.com/document/d/1pN3rukKlAx9VYdVwy9c20g2yVFyIGYGbCEMTC7_W0n0/edit]

**Comment by arielshif** [comment]
this was a largely successful test! make sure to set the properties of this issue (team, priority, etc). start date and end date are not necessary, but are there for you to use if something has a hard deadline.

**Comment by arielshif** [comment]
amy! looks like you assigned this to the election portal team. issue looks great but make sure that you're assigning to comms

**Comment by amyqcs** [comment]
yes you're so right, how do you make a new group?

**Comment by amyqcs** [comment]
figured it out! thanks ariel!
