### ISSUE TITLE
Fix SHAP Arrow Chart Colors + Order

### ISSUE THREAD

**Issue by ashlab11** [BPR-Data-Team/ElectionModel2024-site#71]
Arrows pointing to the right should be blue, and arrows pointing to the left should be red. Also, "other factors" should be the last arrow -- the order should be the same always regardless of how important each is. However, make the order so on average, the most important factors are on top (past elections, campaign finance, polls, expert ratings).

**Comment by arielshif** [comment]
confirm issue closure
