### ISSUE TITLE
Make sure house national has the correct outcome likelihood

### ISSUE THREAD

**Issue by ashlab11** [BPR-Data-Team/ElectionModel2024-site#75]
House national currently shows democrats winning the house but says it happens <50% of the time. This is a difficult thing to deal with, because we have to choose between median/mode. I chose median for individual races and mode for overall national races, which works for senate but not house. I think in the meantime I'm going to choose median, which for NOW works for Senate but likely will not work forever. I'll let Akshay know to restart the API and that should theoretically fix that problem.

**Comment by arielshif** [comment]
confirm issue closure
